Split GH Actions workflow into individual parts, document docker_db.sh and use Oracle EE for CI

diff --git a/.github/workflows/contributor-build.yml b/.github/workflows/contributor-build.yml
--- a/.github/workflows/contributor-build.yml
+++ b/.github/workflows/contributor-build.yml
@@ -4,17 +4,23 @@
 # See https://docs.github.com/en/free-pro-team@latest/actions
 # for more information about GitHub actions.
 
-name: Hibernate ORM build
+name: Hibernate ORM build (disabled)
 
 on:
+# We keep this file just for reference, but disable the execution by using non-existent branch names
+# GitHub Actions does not support publishing artifacts of individual jobs until the workflow completed,
+# and also doesn't support configuring that a job may fail, which leads us to this design,
+# where we define a workflow for each matrix entry
   push:
     branches:
-      - 'main'
-      - 'wip/6.0'
-  pull_request:
+      - 'non-existent'
+#      - 'main'
+#      - 'wip/6.0'
+  pull_request_target:
     branches:
-      - 'main'
-      - 'wip/6.0'
+      - 'non-existent'
+#      - 'main'
+#      - 'wip/6.0'
 jobs:
   build:
     name: Java 8
@@ -41,10 +47,32 @@ jobs:
             experimental: true
           - rdbms: mssql
             experimental: true
+          - rdbms: hana
+            experimental: true
     steps:
       - uses: actions/checkout@v2
+        with:
+          persist-credentials: false
       - name: Reclaim Disk Space
         run: .github/ci-prerequisites.sh
+      - name: Login to Docker Hub
+        uses: docker/login-action@v1
+        if: ${{ matrix.rdbms == 'oracle' || matrix.rdbms == 'hana' }}
+        with:
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_TOKEN }}
+      - name: Start database
+        env:
+          RDBMS: ${{ matrix.rdbms }}
+        run: ci/database-start.sh
+      - name: Start database # After the database started, we can logout so the credentials aren't available anymore
+        run: docker logout
+        if: ${{ matrix.rdbms == 'oracle' || matrix.rdbms == 'hana' }}
+      - uses: actions/checkout@v2 # After the database is running, we can checkout the PR
+        if: ${{ github.event_name == 'pull_request' && (matrix.rdbms == 'oracle' || matrix.rdbms == 'hana') }}
+        with:
+          ref: ${{ github.event.pull_request.head.sha }}
+          persist-credentials: false
       - name: Set up Java 8
         uses: actions/setup-java@v1
         with:
@@ -57,6 +85,8 @@ jobs:
       - name: Cache Maven local repository
         uses: actions/cache@v2
         id: cache-maven
+        # Avoid possible cache poisoning
+        if: ${{ github.event_name == 'push' || (matrix.rdbms != 'oracle' && matrix.rdbms != 'hana') }}
         with:
           path: |
             ~/.m2/repository
@@ -86,6 +116,13 @@ jobs:
     continue-on-error: true
     steps:
       - uses: actions/checkout@v2
+        with:
+          persist-credentials: false
+      - uses: actions/checkout@v2
+        if: ${{ github.event_name == 'pull_request' }}
+        with:
+          ref: ${{ github.event.pull_request.head.sha }}
+          persist-credentials: false
       - name: Set up Java 11
         uses: actions/setup-java@v1
         with:
@@ -98,6 +135,8 @@ jobs:
       - name: Cache Maven local repository
         uses: actions/cache@v2
         id: cache-maven
+        # Avoid possible cache poisoning from PRs
+        if: ${{ github.event_name == 'push' }}
         with:
           path: |
             ~/.m2/repository
